src/Entity/Adoptant.php
<?php

namespace App\Entity;

use App\Repository\AdoptantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdoptantRepository::class)
 */
class Adoptant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity=Adoption::class, mappedBy="adoptant")
     */
    private $adoptions;

    public function __construct()
    {
        $this->adoptions = new ArrayCollection();
    }


    public function __toString()
    {
        $result = $this->telephone;
        return  (string) $result;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection<int, Adoption>
     */
    public function getAdoptions(): Collection
    {
        return $this->adoptions;
    }

    public function addAdoption(Adoption $adoption): self
    {
        if (!$this->adoptions->contains($adoption)) {
            $this->adoptions[] = $adoption;
            $adoption->setAdoptant($this);
        }

        return $this;
    }

    public function removeAdoption(Adoption $adoption): self
    {
        if ($this->adoptions->removeElement($adoption)) {
            // set the owning side to null (unless already changed)
            if ($adoption->getAdoptant() === $this) {
                $adoption->setAdoptant(null);
            }
        }

        return $this;
    }

    public function getFullname()
    {
        return $this->prenom . ' ' . $this->nom;
    }
}

src/Form/AdoptantType.php
<?php

namespace App\Form;

use App\Entity\Adoptant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class AdoptantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
            'label' => 'Nom :',
             'required' => false,
             'attr' => ['placeholder' => 'Poti'],
             ])
            ->add('prenom', TextType::class, [
                'label' => 'Prénom :',
                'required' => false,
                'attr' => ['placeholder' => 'Poutchi'],
                ])
            ->add('adresse', TextType::class,[
                'label' => 'Adresse :',
                'required' => false,
                'attr' => ['placeholder' => '00 avenue des petites patates'],
                ])
            ->add('telephone', TextType::class, [
                'label' => 'Téléphone :',
                'attr' => ['placeholder' => '1234567890'],
            ])
            ->add('email', EmailType::class, [
                'label' => 'E-mail :',
                'required' => false,
                'attr' => ['placeholder' => 'mail@example.com'],
                ])
            ->add('ville', TextType::class, [
                'label' => 'Ville :',
                'attr' => ['placeholder' => 'Paris'],
                'required' => false,
            ])
            ->add('code_postal', IntegerType::class, [
                'label' => 'Code Postal: ',
                'attr' => ['placeholder' => '98745'],
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Adoptant::class,
        ]);
    }
}

src/Controller/AdoptantController.php
<?php

namespace App\Controller;

use App\Entity\Adoptant;
use App\Form\AdoptantType;
use App\Repository\AdoptantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;



/**
 * @Route("/adoptant")
 */
class AdoptantController extends AbstractController
{
    /**
     * @Route("/", name="app_adoptant_index", methods={"GET"})
     */
    public function index(AdoptantRepository $adoptantRepository): Response
    {
        return $this->render('adoptant/index.html.twig', [
            'adoptants' => $adoptantRepository->findAll(),
        ]);
    }

    /**
     * @IsGranted("ROLE_RESPONSABLE_POLE")
     * @Route("/ajout", name="app_adoptant_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AdoptantRepository $adoptantRepository): Response
    {
        $adoptant = new Adoptant();
        $form = $this->createForm(AdoptantType::class, $adoptant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $adoptantRepository->add($adoptant);
            return $this->redirectToRoute('app_adoptant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adoptant/new.html.twig', [
            'adoptant' => $adoptant,
            'form' => $form,
        ]);
    }

    /**
     * @IsGranted("ROLE_RESPONSABLE_POLE")
     * @Route("/{id}", name="app_adoptant_show", methods={"GET"})
     */
    public function show(Adoptant $adoptant): Response
    {
        return $this->render('adoptant/show.html.twig', [
            'adoptant' => $adoptant,
        ]);
    }

    /**
     * @Route("/{id}/modification", name="app_adoptant_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Adoptant $adoptant, AdoptantRepository $adoptantRepository): Response
    {
        $form = $this->createForm(AdoptantType::class, $adoptant);
        $form->handleRequest($request);
        $retour = ($_SERVER['HTTP_REFERER']);
        //dd($retour); // "http://localhost:8000/adoption/302/modification"

        $id = 302;
        if ($form->isSubmitted() && $form->isValid()) {
           
            $adoptantRepository->add($adoptant);
            //dd($_SERVER['HTTP_REFERER']); // "http://localhost:8000/adoptant/335/modification"
            //return $this->redirectToRoute('app_adoptant_index', [], Response::HTTP_SEE_OTHER);
            //TODO redirection vers la page adoption si on en vient
             //header('Location: http://localhost:8000/adoption/' . $id . '/modification');
             header ('Location: ' . $_SERVER['HTTP_REFERER']);

            exit();
 
        }

        return $this->renderForm('adoptant/edit.html.twig', [
            'adoptant' => $adoptant,
            'form' => $form,
        ]);
    }

//     <?php
//     header('Location: http://www.votresite.com/pageprotegee.php');
//     exit();
//

    // TODO Gérer l'archivage
    /**
     * @Route("/{id}", name="app_adoptant_delete", methods={"POST"})
     */
    /* public function delete(Request $request, Adoptant $adoptant, AdoptantRepository $adoptantRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adoptant->getId(), $request->request->get('_token'))) {
            $adoptantRepository->remove($adoptant);
        }

        return $this->redirectToRoute('app_adoptant_index', [], Response::HTTP_SEE_OTHER);
    } */

}

templates/adoptant/_delete_form.html.twig
<form method="post" action="{{ path('app_adoptant_delete', {'id': adoptant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adoptant.id) }}">
    <button class="btn">{{ button_label|default('Delete') }}</button>
</form>

templates/adoptant/_form.html.twig
{% block body %}

	<main class="flex mx-auto ">

		<aside class="h-screen w-full xl:w-2/4 hidden lg:w-11/12 hidden xl:block lg:block lg:w-full h-screen md:hidden sm:hidden sm:w-full h-screen">
			<img class="max-w-full p-10 m-20 md:m-10 pt-20 mt-20" src=" {{ asset('build/images/accueil.png') }} " alt="dog-cat-home">
		</aside>

		<section class="flex mx-auto">

			<div class="flex flex-col p-4 ">

				<div class=" p-4 text-center text-2xl rounded cursor-pointer">
					<p class="border-b-4 text-4xl mt-6 font-bold">
						Créer une nouvelle adoption :
					</p>
				</div>

{{ form_start(form) }}


{{ form_row(form.nom, {'attr': {class:'rounded-md w-full :'}}) }}
{{ form_row(form.prenom, {'attr': {class:'rounded-md w-full :'}}) }}
{{ form_row(form.adresse, {'attr': {class:'rounded-md w-full :'}}) }}
{{ form_row(form.telephone, {'attr': {class:'rounded-md w-full :'}}) }}
{{ form_row(form.email, {'attr': {class:'rounded-md w-full :'}}) }}
{{ form_row(form.ville, {'attr': {class:'rounded-md w-full :'}}) }}
{{ form_row(form.code_postal, {'attr': {class:'rounded-md w-full :'}}) }}

    {{ form_widget(form) }}

    <button class="btn m-20 ml-5 mr-5">{{ button_label|default('Sauvegarde') }}</button>
    <a href="{{ path('app_adoptant_index') }}"><button class="btn m-20 ml-5 mr-5">Ajouter une adoption</button></a>


{{ form_end(form) }}

{% endblock %}

templates/adoptant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Adoptant{% endblock %}

{% block body %}
<main class="flex justify-center items-center  ">

      <section class=" border-2 p-10  ml-2">
      <div class="px-10 md:px-12 py-10 md:py-7">
      <div class="flex items-center justify-between">
                <p tabindex="0" class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800">Edit Adoptant </p>
                </div>
       </div>
    

    {{ include('adoptant/_form.html.twig', {'button_label': 'Update'}) }}

    <a  href="{{ path('app_adoptant_index') }}">back to list</a>

    {# {{ include('adoptant/_delete_form.html.twig') }} #}
</div >
</section >
</main >
{% endblock %}

templates/adoptant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adoptant index
{% endblock %}

{% block body %}
	<main class="flex w-full ">

		<section
			class="w-full p-4  ml-2 ">
			<!-- ************************header table*********************** -->

			<div class="px-4 md:px-10  py-4 md:py-7">
				<div class="flex  items-center justify-center">
					<p tabindex="0" class="focus:outline-none text-2xl sm:text-2xl md:text-2xl lg:text-4xl font-bold leading-normal text-gray-800">Liste des adoptants
						<span class="material-icons">pets</span>
					</p>
					{# <div class="py-3 px-4 mb-4 flex items-center rounded-xl text-sm font-bold leading-none text-gray-600 bg-white border-2 border-black group-hover:bg-green-blue cursor-pointer rounded">
																																																		                    <p>Sort By:</p>
																																																		                    <select aria-label="select" class="focus:text-noir focus:outline-none bg-transparent ml-1 rounded-xl">
																																																		                        <option class="text-sm text-noir rounded-xl">Latest</option>
																																																		                        <option class="text-sm text-noir rounded-xl">Oldest</option>
																																																		                        <option class="text-sm text-noir rounded-xl">Latest</option>
																																																		                    </select>
																																																		                </div> #}

				</div>
			</div>
			<div class=" py-4 md:py-7 px-4 md:px-8 xl:px-10">
				<div class="sm:flex items-center justify-between mb-4 w-full">
					<p class="text-sm font-bold leading-none text-white ">
						<a class="text-sm font-bold leading-none " href="{{ path('app_adoptant_new') }}">
							<button class="bg-white rounded p-4 text-md font-normal leading-none text-black border-double border-2 border-black shadow-lg shadow-green-blue  hover:bg-green-blue  hover:-translate-y-1 hover:scale-110 hover:text-white font-bold">{{ button_label|default('Créer') }}</button>
						</a>
					</p>
				</div>
				<h1></h1>
				<!--************************************** table******************************* -->

				<table class="min-w-full border-collapse block md:table ">
					<thead class="block md:table-header-group">
						<tr class="border border-grey-500  md:border-none block md:table-row absolute -top-full md:top-auto -left-full md:left-auto  md:relative ">
							<th class="bg-gray-600 p-2 text-white font-bold md:border md:border-grey-500 text-left block md:table-cell">Id
							</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Nom</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Prénom</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Adresse</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Téléphone</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Email</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Ville</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Code postal</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Actions</th>

						</tr>
					</thead>
					{# //**************** #}

					<tbody class="block  md:table-row-group ">
						{% for adoptant in adoptants %}

							<tr class="bg-gray-300 border border-grey-500 md:border-none block md:table-row">
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">ID</span>
									{{ adoptant.id }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Nom</span>
									{{ adoptant.nom }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Prenom</span>
									{{ adoptant.prenom }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Address</span>
									{{ adoptant.adresse }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Telephone
									</span>
									{{ adoptant.telephone }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Email</span>
									{{ adoptant.email }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Ville</span>
									{{ adoptant.ville }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Code Postal</span>
									{{ adoptant.codePostal }}</td>

								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Actions</span>
									<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 border border-blue-500 rounded">
										<a href="{{ path('app_adoptant_show', {'id': adoptant.id}) }}">Détails</a>
									</button>
									{% if is_granted('ROLE_RESPONSABLE_POLE') %}
										<button class="bg-green-400 hover:bg-green-400 text-white font-bold py-1 px-2 border bord-bg-green-400 rounded">
											<a href="{{ path('app_adoptant_edit', {'id': adoptant.id}) }}">Modifier</a>
										</button>
									{% endif %}
									{# <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 border border-red-500 rounded">Archive</button> #}
								</td>
							</tr>
						</td>
					</tbody>
				</tr>

			{% else %}
				<tr>
					<td colspan="9">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</section></main>{% endblock %}

templates/adoptant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Adoptant{% endblock %}

{% block body %}
<main class="flex justify-center items-center  ">

      <section class=" border-2 p-10  ml-2">
      <div class="px-10 md:px-12 py-10 md:py-7">
      <div class="flex items-center justify-between">
                <p tabindex="0" class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800"></p>
                </div>
       </div>
       <!-- ************************header table*********************** -->



    {{ include('adoptant/_form.html.twig') }}

    </div >
</section >
</main >
{% endblock %}

templates/adoptant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adoptant{% endblock %}

{% block body %}
<main class="flex justify-center items-center  ">

      <section class=" border-2 p-10  ml-2">
      <div class="px-10 md:px-12 py-10 md:py-7">
      <div class="flex items-center justify-between">
                <p tabindex="0" class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800">Adoptant </p>
                </div>
       </div>
       <!-- ************************header table*********************** -->
    

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adoptant.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ adoptant.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ adoptant.prenom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ adoptant.adresse }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ adoptant.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ adoptant.email }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ adoptant.ville }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ adoptant.codePostal }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_adoptant_index') }}">back to list</a>

    <a href="{{ path('app_adoptant_edit', {'id': adoptant.id}) }}">edit</a>
    </div >
</section >
</main >

    {# {{ include('adoptant/_delete_form.html.twig') }} #}
{% endblock %}